version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_TUNNEL_URL=https://glowing-garbanzo-jrv94vjgwjx2px9q-5678.app.github.dev
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:

